schema_version: 1

context:
  name: langgraph-sdk
  version: "0.2.10"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/langgraph_sdk-${{ version }}.tar.gz
  sha256: ab58331504fbea28e6322037aa362929799b4e9106663ac1dbd7c5ac44558933

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - hatchling
    - pip
  run:
    - python >=${{ python_min }},<4.0.0,<4.0
    - httpx >=0.25.2
    - orjson >=3.10.1
tests:
  - python:
      imports:
        - langgraph_sdk
      pip_check: true

      python_version: ${{ python_min }}.*
about:
  summary: SDK for interacting with LangGraph API
  license: MIT
  license_file: LICENSE
  homepage: https://www.github.com/langchain-ai/langgraph

extra:
  recipe-maintainers:
    - jan-janssen
