schema_version: 1

context:
  name: langgraph-sdk
  version: "0.3.5"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/langgraph_sdk-${{ version }}.tar.gz
  sha256: 64669e9885a908578eed921ef9a8e52b8d0cd38db1e3e5d6d299d4e6f8830ac0

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - hatchling
    - pip
  run:
    - python >=${{ python_min }},<4.0.0,<4.0
    - httpx >=0.25.2
    - orjson >=3.10.1
tests:
  - python:
      imports:
        - langgraph_sdk
      pip_check: true

      python_version: ${{ python_min }}.*
about:
  summary: SDK for interacting with LangGraph API
  license: MIT
  license_file: LICENSE
  homepage: https://www.github.com/langchain-ai/langgraph

extra:
  recipe-maintainers:
    - jan-janssen
